In [1]:
import pandas as pd

df = pd.read_parquet("exports/parquet/d_customers.parquet")
df.head()

,customer_id,country_name,first_invoice_date,_loaded_at,_source_file
0,13152,United Kingdom,2010-01-14,2026-05-31 19:25:27.476757,online_retail_II.xlsx
1,14964,United Kingdom,2011-04-06,2026-05-31 19:25:27.476757,online_retail_II.xlsx
2,17839,United Kingdom,2011-10-28,2026-05-31 19:25:27.476757,online_retail_II.xlsx
3,12797,Portugal,2010-10-11,2026-05-31 19:25:27.476757,online_retail_II.xlsx
4,14867,United Kingdom,2009-12-05,2026-05-31 19:25:27.476757,online_retail_II.xlsx

In [2]:
df = pd.read_parquet("exports/parquet/d_dates.parquet")
df.head()

,date_id,full_date,year,quarter,month,day,week,_loaded_at,_source_file
0,20091201,2009-12-01,2009,4,12,1,49,2026-05-31 19:35:54.031502,calendar
1,20091202,2009-12-02,2009,4,12,2,49,2026-05-31 19:35:54.031502,calendar
2,20091203,2009-12-03,2009,4,12,3,49,2026-05-31 19:35:54.031502,calendar
3,20091204,2009-12-04,2009,4,12,4,49,2026-05-31 19:35:54.031502,calendar
4,20091205,2009-12-05,2009,4,12,5,49,2026-05-31 19:35:54.031502,calendar

In [3]:
df = pd.read_parquet("exports/parquet/d_products.parquet")
df.head()

,product_id,stock_code,product_description,_loaded_at,_source_file
0,1,10002,INFLATABLE POLITICAL GLOBE,2026-05-31 19:25:27.476757,online_retail_II.xlsx
1,2,10080,GROOVY CACTUS INFLATABLE,2026-05-31 19:25:27.476757,online_retail_II.xlsx
2,3,10109,BENDY COLOUR PENCILS,2026-05-31 19:25:27.476757,online_retail_II.xlsx
3,4,10120,DOGGY RUBBER,2026-05-31 19:25:27.476757,online_retail_II.xlsx
4,5,10123C,HEARTS WRAPPING TAPE,2026-05-31 19:25:27.476757,online_retail_II.xlsx

In [4]:
df = pd.read_parquet("exports/parquet/f_transactions.parquet")
df.head()

,transaction_id,invoice_no,customer_id,product_id,date_id,quantity,unit_price,revenue,_loaded_at,_source_file
0,1,489434,13085,619,20091201,24,1.25,30.0,2026-05-31 19:25:27.476757,online_retail_II.xlsx
1,2,489434,13085,861,20091201,10,5.95,59.5,2026-05-31 19:25:27.476757,online_retail_II.xlsx
2,3,489434,13085,1144,20091201,24,1.25,30.0,2026-05-31 19:25:27.476757,online_retail_II.xlsx
3,4,489434,13085,1254,20091201,48,2.10,100.8,2026-05-31 19:25:27.476757,online_retail_II.xlsx
4,5,489434,13085,1277,20091201,24,1.65,39.6,2026-05-31 19:25:27.476757,online_retail_II.xlsx

In [5]:
# Размеры всех витрин
files = [
    "d_customers",
    "d_dates",
    "d_products",
    "f_transactions"
]

for name in files:
    df = pd.read_parquet(f"exports/parquet/{name}.parquet")
    print(name, df.shape)

d_customers (5878, 5)
d_dates (739, 9)
d_products (4631, 5)
f_transactions (779421, 10)

In [6]:
# df.head() показывает только первые 5 строк, а не всю таблицу.
# чтобы показалось больше строк нужно прописать df.head(50)